blog/urls.py
from django.urls import path 
from . import views 
from .feed import LatestPostsFeed
app_name = 'blog  ' 

urlpatterns = [
    path('',views.post_list_page,name='posts_list'),
    path('posts/',views.PostListPage.as_view(),name='posts_list_view'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>',views.post_details_page,name='post_details'),
    path("share/<int:id>/",views.post_share,name='post_share'),
    path('posts/tag__<slug:tag_slug>',views.post_list_by_tag,name='post_by_slug'),
    path('search/',views.post_search,name='post_search'),

    path('feed/', LatestPostsFeed(), name='post_feed'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include 
##sitemaps
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap
sitemaps = {
'posts': PostSiteMap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse 

from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
	STATUS_CHOUICES =(

		('draft','Draft'),
		('published','Published')
		)	
	title = models.CharField(max_length=300)
	body = models.TextField(null=True)
	slug = models.SlugField(max_length=300,unique_for_date='publish')
	author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
	publish = models.DateTimeField(default=timezone.now())
	status = models.CharField(max_length=10,choices=STATUS_CHOUICES,default='draft')

	objects  = models.Manager()
	published = PublishedManager()


	##adding a third apary taggin manager 
	tags = TaggableManager()

	def __str__(self):
		return self.title[0:20]

	
	def get_absolute_url(self):
		return reverse('blog:post_details',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])
	class Meta:

		ordering = ('-publish',)
class ActiveCommentManager(models.Manager):
	def get_queryset(self):
		return super(ActiveCommentManager,self).get_queryset().filter(active=True)
class Comment(models.Model):
	title = models.CharField(max_length=100)
	body = models.TextField()
	email = models.EmailField()
	user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comments')
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='post_comments')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)
	objects = models.Manager()
	ActiveManager = ActiveCommentManager()
	class Meta:
		ordering = ("created",)
	def __str__(self):
		return self.user.username +" on "+self.post.title[0:20]
	

blog/forms.py
from django import forms 
from .models import Post , Comment 
class CommentForm(forms.ModelForm):
    class Meta :
        model = Comment 
        fields = ['title','email','body']
        
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=120,widget=forms.widgets.EmailInput)
    to = forms.EmailField(max_length=120)
    comments = forms.CharField(required=False,max_length=200,widget=forms.widgets.Textarea)
class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render,get_object_or_404 
from django.core.paginator import PageNotAnInteger,EmptyPage,Paginator
from django.views.generic import ListView
from .models import Post,Comment 
from .forms import EmailPostForm,CommentForm

##django aggregation 

from django.db.models import Count
##

from django.core.mail import send_mail

##third pary taggin app 
from taggit.models import Tag
# Create your views here.
##adding search 
from django.contrib.postgres.search import SearchVector ,SearchQuery,SearchRank
from django.contrib.postgres.search import TrigramSimilarity
##
def post_search(request):
    q = request.GET.get('q')
    posts = None 
    if q:
        search_query = SearchQuery(q)
        search_vector = SearchVector('title',weight='A')+SearchVector('body',weight='B')
        
        # posts = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')
        # posts = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3).order_by('-rank')
        
        posts = Post.published.annotate(similarity = TrigramSimilarity('title',q )).filter(similarity__gt=0.1).order_by("-similarity")
    else:
        q='None'
    context = {
        'posts':posts,
        'query':q

    }
    return render(request, 'blog/post_list.html',context) 
def post_list_by_tag(request,tag_slug=None):
    object_lst = Post.published.all()
    pots = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_lst = object_lst.filter(tags__in=[tag])
        posts = object_lst
    context = {
        'posts':posts

    }
    return render(request, 'blog/post_list.html',context)    
def post_share(request,id):
    post = get_object_or_404(Post,id=id,status='published')
    form = EmailPostForm(request.POST or None)
    sent = False 
    if request.method=='POST':
        if form.is_valid():
            data = form.cleaned_data 
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{data['name']} recommends  you to read this post ' {post.title}' "
            message = f"read it from here {post_url} \n\n {data['name']} says this about it  \n\n------------------\n\n{data['comments']}\n\n------------------"
            my_email = 'chihab.me.dev@gmail.com'
            to = data['to']
            send_mail(subject, message, my_email,[to], fail_silently=False)
            sent = True 
            form = EmailPostForm()
    context = {
        'post':post,
        'form':form,
        'sent':sent
    }
    return render(request,'blog/post_share.html',context)
class PostListPage(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2 ; 
    template_name = 'blog/post_list.html'
def post_list_page(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 4)
    page = request.GET.get('page')
    try :
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context  = {
        "posts":posts,
        'posts':posts
    }
    return render(request,'blog/post_list.html',context)
def post_details_page(request,year,month,day,slug):
    obj =  get_object_or_404(Post,slug=slug,publish__year=year,publish__month=month,publish__day=day,status='published')
    comments =  obj.post_comments.filter(active=True)
    form = CommentForm(request.POST or None )
    new_comment =None
    ##adding recommendation system 
    post_tags_ids = obj.tags.values_list("id",flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)
    similar_posts=similar_posts.exclude(id=obj.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by("-same_tags",'-publish')[0:6]
    
    ###
    if request.method=='POST':
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post  = obj 
            new_comment.user = request.user 
            new_comment.save()
            form = CommentForm()
     
    context = {
        'post':obj ,
        'comments':comments,
        'new_comment':new_comment,
        'comment_form':form,
        'similar_posts':similar_posts
    }
    return render(request,'blog/detail.html',context)

blog/templates/base.html
{% load static %}
{% load blog_tags %}
<html>

<head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


</head>

<body>
    <h1> this is my personal blog i have writing {%  total_posts  %} posts </h1>
    <div class='container'>
        <div class='side--bar'>
            {% latest_posts %}
            <div class='most--commented'>

                <h4>most commented posts</h4>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                {% for post in most_commented_posts %}
                <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> 
                <p>{{post.post_comments.count}} comment</p>
                </li>
                {% endfor %}
            </div>
        </div>
    
        <main class='main--body'>
            {% block content %}

            {% endblock content %}
        </main>
    </div>

    <style>
        .container {
            width:100% !important; 
            display: flex;

        }

        .side--bar {
            flex: 0.6;
            display:flex;
            flex-direction:column;
            gap:20px;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>

</body>

</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load crispy_forms_tags %}

{% block title %}{{post.title}}{% endblock title %}
{% block content %}
{{post.title |linebreaks}}
<p>
    {% comment %}
    {{post.body|markdown}}
    {% endcomment %} 
    {{post.body |allFirstToCapital}}
</p>
published on {{post.publish}} by {{post.author}} 
</br>
<a  href="{% url 'blog:post_share' post.id %}" class="btn btn-default_if_none">share this post</a>
    
    {% with comments.count as total_comments %}
    
    <h2>
    
        {{total_comments}} comment{{total_comments|pluralize}}
    </h2>
    
    {% endwith %}
    <form method='post' >
 
        {%  crispy   comment_form     %}
        <input class='btn btn-success' type='submit' value='comment' />

    </form>
    {% if new_comment %}
        <h2>you comment has been saved successfully</h2>
    {% else %}
    <h4>let us know want your think about this ! </h4>

    {% endif %}
    <div class='comments'>
        {%  for comment in comments %}
        <div>

            <h3> comment {{forloop.counter}} by {{comment.user.username}}</h3>
            <h4>title : {{comment.title}}</h4>
            <p>
                {{comment.body|linebreaks}}
            </p>
            {% empty %}
            <h2>there is no comment<h2>
        </div>

        {% endfor  %}
    </div>
    <div class='similar__posts'>
        <h3>your also may like  </h3>
        {% for post in similar_posts %}
        <div class='similar__post'>
            <a href='{{post.get_absolute_url}}'>{{post.title}}</a>

        </div>
        {%  empty %}
        <h4> we don't have anything to recommend yet </h4>
        {% endfor %}
    </div>
{% endblock content %}

blog/templates/blog/latest_posts.html
<ul>
<li><h3>latest posts</h3></li>
    {% for post in latest_posts %}

<li><a href='{{post.get_absolute_url}}'> {{post.title}}</a></li>

{% endfor %}
</ul>

blog/templates/blog/pagination.html
<div class='pagination--wrapper'>
    {% if page.has_previous %}
    <a href='?page={{page.previous_page_number}}'>prev</a>
    {% endif %}
    <span class='pagination--current'>{{page.number}} of {{page.paginator.num_pages}}</span>
    {% if page.has_next %}
    <a href='?page={{page.next_page_number}}'>next</a>
    {% endif %}
    </div>

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method='get' action='{% url "blog:post_search" %}'>
    <input name='q' type='text' />
    <button class='btn btn-success'>search</button>

</form>

{% if query %}
<h4>searching on <strong>{{query}}</strong></h4>
{% with posts.count as total %}
<h6>found {{total}} match{{total|pluralize}}</h6>
{% endwith %}
{% endif %}
<ul>

    {% for post in posts  %}
<li>
    <h6>posts {{forloop.counter}}<h6>
    <a href={{post.get_absolute_url}}>{{post.title}}</a>
</li>
<h8>
    Taggs : 
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:post_by_slug' tag.slug %} ">{{tag.name}}</a>
    {% if not forloop.last %} , {% endif %}
    {% endfor %}
</h8>
{% empty %}
    <h3> there is no posts to show</h3>
{% endfor  %}
</br></br></br></br></br></br></br>
{% if page_obj %}

<h1>you are using class based view</h1>

{% include './pagination.html' with page=page_obj %}
{% else %}
<h1>you are using function based view</h1>

{% include './pagination.html' with page=posts %}
{% endif %}
</ul>
{% endblock content %}

blog/templates/blog/post_share copy.html
{%  extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title  %}share {{post.title}}{% endblock title %}

{% block content %}
<div class='share__page'>
{{post.title}}
published on {{post.publish}} by {{post.author}}
</br>
<form method='post'>
    {% csrf_token %} 
    {% crispy form %}
    <button type="button" class="btn btn-success">share</button>

</from>
    {% if sent %}
your email has been sent successfully  
{% endif %}
</div>
<style>
    .share__page{
        padding-top:3rem;   
        gap:1rem;
        width:100%;
        display:flex;
        justify-content:center;
        flex-direction:column;
        align-items:center;
    }

</style>
{% endblock content  %}

blog/templates/blog/post_share.html
{%  extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title  %}share {{post.title}}{% endblock title %}

{% block content %}
<div class='share__page'>
{{post.title}}
published on {{post.publish}} by {{post.author}}
</br>
<form method='post'>
    {% csrf_token %} 
    {% crispy form %}
    <button type="button" class="btn btn-success">share</button>

</from>
    {% if sent %}
your email has been sent successfully  
{% endif %}
</div>
<style>
    .share__page{
        padding-top:3rem;   
        gap:1rem;
        width:100%;
        display:flex;
        justify-content:center;
        flex-direction:column;
        align-items:center;
    }

</style>
{% endblock content  %}